# Setup
title:        "Food Analytica"
tagline:      "An interactive Datastory of social status and health"
baseurl:      "jalil-M.github.io"
locale:       "en"


# About/contact
author:
  name:       "Abdeljalil Moussa"
  url:        "jalil-M.github.io"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
